kind: Service
apiVersion: v1
metadata:
  name: kubemanage-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 60000
---
kind: Endpoints
apiVersion: v1
metadata:
  name: kubemanage-service
subsets:
  - addresses:
      - ip: 172.16.189.19
    ports:
      - port: 60000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubemanage-ingress
spec:
  rules:
    - host: ipistest.etor.top
      http:
        paths:
          - path: /api/kubemanage
            backend:
              serviceName: kubemanage-service
              servicePort: 80
